branches:
  - master

host:
  distro: fedora/24/atomic

tests:
  # https://bugzilla.redhat.com/show_bug.cgi?id=1318547#c7
  - mount --make-rshared /
  - systemctl start docker
  - ostree admin unlock
  - >
      docker run --privileged
      -v /root:/root -v $PWD:/code -v /:/host
      --workdir /code fedora:24 ./rhci.sh
  - PYTHON=python3 ./test.sh

artifacts:
  - tests.log
